FEAT: Latest git submodule testing :cake:

diff --git a/.github/workflows/run_tests.yml b/.github/workflows/run_tests.yml
--- a/.github/workflows/run_tests.yml
+++ b/.github/workflows/run_tests.yml
@@ -18,11 +18,79 @@ jobs:
         uses: actions/setup-python@v4
         with:
           python-version: "3.10"
+          submodules: 'recursive'
       - name: Test pre-commit hooks
         run: |
           python -m pip install --upgrade pip
           pip install pre-commit
           pre-commit run
+  test-latest-submodules:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout repository with submodules
+        uses: actions/checkout@v3
+        with:
+          submodules: 'recursive'
+          # This fetches only a single branch by default, so additional fetch is needed
+          fetch-depth: 0 # Optionally, set to 0 to fetch all history for all branches and tags
+
+      - name: Determine current branch or PR ref
+        id: get_branch
+        run: |
+          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
+            echo "BRANCH_NAME=${{ github.event.pull_request.base.ref }}" >> $GITHUB_ENV
+          else
+            echo "BRANCH_NAME=$(echo $GITHUB_REF | sed 's|refs/heads/||')" >> $GITHUB_ENV
+          fi
+          echo $BRANCH_NAME
+        shell: bash
+
+      - name: Initialize and update submodule
+        run: |
+          git submodule update --init --recursive
+
+      - name: Check if submodules are up to date
+        shell: bash
+        run: |
+          NOTEBOOKS_PATH=docs/notebooks
+          FAQ_PATH=docs/faq
+
+          # Checking out Notebooks submodule with the same branch as the main project
+          echo "Checking $NOTEBOOKS_PATH for updates..."
+          cd $NOTEBOOKS_PATH
+          echo $(git fetch --all --verbose)
+          echo $(git remote get-url origin)
+          git checkout origin/$BRANCH_NAME
+          if git show-ref --verify refs/remotes/origin/$BRANCH_NAME; then
+           echo "Branch $BRANCH_NAME exists."
+          else
+            echo "::error::Branch $BRANCH_NAME does not exist on remote."
+            exit 1
+          fi
+          NOTEBOOKS_LATEST_COMMIT=$(git rev-parse refs/remotes/origin/${{ env.BRANCH_NAME }})
+          NOTEBOOKS_CURRENT_COMMIT=$(git rev-parse HEAD)
+          
+          
+          cd ../..
+          if [ "$NOTEBOOKS_LATEST_COMMIT" != "$NOTEBOOKS_CURRENT_COMMIT" ]; then
+            echo "::error ::Submodule $NOTEBOOKS_PATH is not up to date with the ${{ env.BRANCH_NAME }} branch. Please update it."
+            exit 1
+          else
+            echo "Submodule $NOTEBOOKS_PATH is up to date with the ${{ env.BRANCH_NAME }} branch."
+          fi
+
+          # Checking FAQs only on the develop branch.
+          echo "Checking $FAQ_PATH for updates..."
+          cd $FAQ_PATH
+          FAQ_LATEST_COMMIT=$(git rev-parse origin/develop)
+          FAQ_CURRENT_COMMIT=$(git rev-parse HEAD)
+          cd ../..
+          if [ "$FAQ_LATEST_COMMIT" != "$FAQ_CURRENT_COMMIT" ]; then
+            echo "::error ::Submodule $FAQ_PATH is not up to date. Please update it."
+            exit 1
+          else
+            echo "Submodule $FAQ_PATH is up to date."
+          fi
   build:
     name: test ${{ matrix.python-version }} - ${{ matrix.platform }}
     runs-on: ${{ matrix.platform }}
