Only trigger on PRs

diff --git a/.github/workflows/tidy3d-python-client-tests.yml b/.github/workflows/tidy3d-python-client-tests.yml
--- a/.github/workflows/tidy3d-python-client-tests.yml
+++ b/.github/workflows/tidy3d-python-client-tests.yml
@@ -138,7 +138,7 @@ jobs:
   verify-schema-change:
     name: verify-schema-change
     needs: determine-test-scope
-    if: ( needs.determine-test-scope.outputs.local_tests == 'true' ) || ( needs.determine-test-scope.outputs.remote_tests == 'true' )
+    if: (( needs.determine-test-scope.outputs.local_tests == 'true' ) || ( needs.determine-test-scope.outputs.remote_tests == 'true' )) && (github.event_name == "pull_request") 
     runs-on: ubuntu-latest
     container: ghcr.io/astral-sh/uv:debian
     defaults:
@@ -427,7 +427,7 @@ jobs:
       ( needs.determine-test-scope.outputs.pr_approval_state == 'true' ) && 
       ( needs.determine-test-scope.outputs.local_tests == 'true' ) || 
       ( needs.determine-test-scope.outputs.remote_tests == 'true' )
-    needs: [local-tests, remote-tests, lint]
+    needs: [local-tests, remote-tests, lint, verify-schema-change]
     runs-on: ubuntu-latest
     steps:
       - name: check-passing-remote-tests
@@ -437,6 +437,9 @@ jobs:
 
           if [[ "${{ needs.lint.result }}" != 'success' ]]; then
             echo "❌ Linting failed or was skipped."
+            exit 1
+          elif [[ "${{ needs.verify-schema-change.result }}" != 'success' ]]; then
+            echo "❌ verify-schema-change failed or was skipped."
             exit 1
           elif [[ "${{ needs.remote-tests.result }}" != 'success' ]]; then
             echo "❌ remote-tests failed or were skipped."
