fix: develop schema updates

diff --git a/.github/workflows/tidy3d-python-client-tests.yml b/.github/workflows/tidy3d-python-client-tests.yml
--- a/.github/workflows/tidy3d-python-client-tests.yml
+++ b/.github/workflows/tidy3d-python-client-tests.yml
@@ -151,22 +151,23 @@ jobs:
       run:
         shell: bash
     steps:
-      - name: checkout-pr-branch
+      - name: checkout-branch
         uses: actions/checkout@v4
         with:
-          path: 'pr' 
-
-      - name: checkout-develop-branch
-        uses: actions/checkout@v4
-        with:
-          ref: develop 
-          path: 'develop' 
-
+          ref: ${{ github.event.pull_request.head.ref }}
+          repository: ${{ github.event.pull_request.head.repo.full_name }}
+          fetch-depth: '0'
+      
+      - name: git-config
+        run: |
+          cd $GITHUB_WORKSPACE
+          git config --global --add safe.directory $GITHUB_WORKSPACE
+      
       - name: install-depedencies
         run: |
           uv venv $GITHUB_WORKSPACE/.venv -p 3.11
           source $GITHUB_WORKSPACE/.venv/bin/activate
-          uv pip install -e "$GITHUB_WORKSPACE/pr"
+          uv pip install -e "$GITHUB_WORKSPACE"
       
       - name: get-tidy3d-version
         id: get-version
@@ -180,21 +181,24 @@ jobs:
         run: |
           echo "Regenerating schema to check if committed files are up-to-date..."
           source $GITHUB_WORKSPACE/.venv/bin/activate
-          python $GITHUB_WORKSPACE/pr/scripts/regenerate_schema.py
-
-          echo "Checking for differences..."
-          cd pr
-          git diff --exit-code -- tidy3d/schemas
+          python $GITHUB_WORKSPACE/scripts/regenerate_schema.py
+    
+          cd $GITHUB_WORKSPACE
+          echo "Checking for differences with HEAD commit..."
+          git status
+          git log
+          git diff HEAD --name-status --exit-code -- $GITHUB_WORKSPACE/schemas
           echo "✅ Committed schema is up-to-date."
      
       - name: run-schema-diff
         id: schema-diff
         run: |
+          set -e
           # Use git diff to compare the two directories and get a list of changes
           # The command exits with 0 if no changes, 1 if changes are found.
           # We use '|| true' to prevent the workflow from stopping here on failure.
-          cd $GITHUB_WORKSPACE/develop
-          diff_output=$(git diff --no-index --name-status $GITHUB_WORKSPACE/develop/schemas $GITHUB_WORKSPACE/pr/schemas || true)
+          cd $GITHUB_WORKSPACE
+          diff_output=$(git diff origin/develop --name-status -- $GITHUB_WORKSPACE/schemas || true)
 
           # Check if there are any changes
           if [ -z "$diff_output" ]; then
@@ -204,7 +208,7 @@ jobs:
           fi
 
           # If there are changes, create a Markdown table
-          echo "❌ Schema has changed! Please regenerate and commit the changes."
+          echo "❌ Schema has changed compared to develop! Please regenerate and commit the changes."
           echo "changed=true" >> $GITHUB_OUTPUT
 
           # Write the report to the GitHub Step Summary
@@ -214,7 +218,7 @@ jobs:
           
           echo "$diff_output" | while read -r line; do
             status_code=$(echo "$line" | cut -f1)
-            file_path=$(echo "$line" | cut -f2 | sed 's#pr/tidy3d/schemas/##') # Clean up path
+            file_path=$(echo "$line" | cut -f2 | sed 's#tidy3d/schemas/##') # Clean up path
             
             case $status_code in
               "A") status="Added 🟢";;
@@ -229,6 +233,7 @@ jobs:
       - name: verify-allowed-changes
         if: steps.schema-diff.outputs.changed == 'true'
         run: |
+          set -e
           version="${{ steps.get-version.outputs.version }}"
           if [[ "$version" == *rc* ]]; then
             echo "✅ Passing: Schema changed on a release candidate version ($version), which is permitted."
