feat(tidy3d): FXC-3573 add mypy to CI

diff --git a/.github/workflows/tidy3d-python-client-tests.yml b/.github/workflows/tidy3d-python-client-tests.yml
--- a/.github/workflows/tidy3d-python-client-tests.yml
+++ b/.github/workflows/tidy3d-python-client-tests.yml
@@ -171,7 +171,33 @@ jobs:
         run: ruff format --check --diff
       - name: Run ruff check
         run: ruff check tidy3d
-  
+
+  mypy:
+    name: static-type-checks (mypy)
+    needs: determine-test-scope
+    if: needs.determine-test-scope.outputs.code_quality_tests == 'true'
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          fetch-depth: 1
+          submodules: false
+          persist-credentials: false
+
+      - name: set-python-3.10
+        uses: actions/setup-python@v4
+        with:
+          python-version: '3.10'
+
+      - name: Install mypy
+        run: |
+          python -m pip install --upgrade pip
+          pip install "mypy==1.13.0"
+
+      - name: Run mypy
+        run: |
+          mypy --config-file=pyproject.toml
+
   zizmor:
     name: Run zizmor 🌈
     runs-on: ubuntu-latest
@@ -637,6 +663,7 @@ jobs:
       - local-tests
       - remote-tests
       - lint
+      - mypy
       - verify-schema-change
       - lint-commit-messages
       - lint-branch-name
@@ -655,6 +682,12 @@ jobs:
         if: ${{ needs.lint.result != 'success' }}
         run: |
           echo "❌ Linting failed."
+          exit 1
+
+      - name: check-mypy-result
+        if: ${{ needs.determine-test-scope.outputs.code_quality_tests == 'true' && needs.mypy.result != 'success' }}
+        run: |
+          echo "❌ Mypy type checking failed."
           exit 1
           
       - name: check-schema-change-verification
